-- ==============================================================================
-- INVITATION SYSTEM & AUTOMATIC ROLE ASSIGNMENT
-- ==============================================================================

-- 1. INVITATIONS TABLE
-- Stores pending invitations generated by admins
CREATE TABLE IF NOT EXISTS invitations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL,
  role_id UUID REFERENCES roles(id) ON DELETE CASCADE,
  token UUID DEFAULT gen_random_uuid(), -- The secret token for the link
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'expired')),
  created_by UUID REFERENCES auth.users(id),
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Enable RLS
ALTER TABLE invitations ENABLE ROW LEVEL SECURITY;

-- Policies for Invitations
-- Admins/Owners can view and create invitations
-- Public (anonymous) needs to read specific invitation by token (for the accept page)
CREATE POLICY "Admins can manage invitations" ON invitations
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM user_roles ur
      JOIN roles r ON ur.role_id = r.id
      WHERE ur.user_id = auth.uid() AND (r.name = 'owner' OR r.name = 'admin')
    )
  );

CREATE POLICY "Public can read invitations by token" ON invitations
  FOR SELECT
  USING (true); -- We filter by token in the query, so this is open but low risk if token is UUID

-- 2. AUTOMATIC USER SETUP TRIGGER
-- This trigger runs when a new user signs up via Supabase Auth
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
DECLARE
  v_invitation invitations%ROWTYPE;
  v_role_id UUID;
BEGIN
  -- 1. Check if there is a pending invitation for this email
  SELECT * INTO v_invitation
  FROM invitations
  WHERE email = NEW.email AND status = 'pending'
  LIMIT 1;

  -- 2. Create Profile (Always do this)
  INSERT INTO public.profiles (id, email, name, status)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email, '@', 1)),
    'active'
  );

  -- 3. If invitation exists, assign role and mark accepted
  IF v_invitation.id IS NOT NULL THEN
    -- Assign Role
    INSERT INTO public.user_roles (user_id, role_id)
    VALUES (NEW.id, v_invitation.role_id);

    -- Update Invitation
    UPDATE public.invitations
    SET status = 'accepted', updated_at = now()
    WHERE id = v_invitation.id;
  
  ELSE
    -- Optional: Assign default role (e.g., Viewer) if no invitation?
    -- For now, we leave them without role or assign a default 'viewer' if desired.
    -- Let's find 'viewer' role or fallback to nothing.
    SELECT id INTO v_role_id FROM public.roles WHERE name = 'viewer' LIMIT 1;
    
    IF v_role_id IS NOT NULL THEN
        INSERT INTO public.user_roles (user_id, role_id)
        VALUES (NEW.id, v_role_id);
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. BIND TRIGGER TO AUTH.USERS
-- Drop if exists to avoid errors on re-run
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
